- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Deploy index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
  notify: Restart Nginx

- name: Ensure Nginx service is started and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Deploy custom index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{ nginx_web_root }}/index.html"
  notify: Restart Nginx

