- name: Install NTP package
  ansible.builtin.package:
    name: "{{ 'ntp' if ansible_os_family == 'Debian' else 'chrony' }}"
    state: present

- name: Deploy NTP configuration
  ansible.builtin.template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify: Restart NTP service

- name: Ensure NTP service is started and enabled
  ansible.builtin.service:
    name: "{{ 'ntp' if ansible_os_family == 'Debian' else 'chronyd' }}"
    state: started
    enabled: yes

